name: Update Recent Activity
on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: JasonEtco/activity-box@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_MSG: "docs: Update recent activity"
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update recent activity"