name: WakaTime Stats Update
on:
  schedule:
    - cron: '0 23 * * *' # Runs daily at 11 PM UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_OS: "True"
          SHOW_PROJECTS: "True"
          SHOW_EDITORS: "True"
          SHOW_LANGUAGES: "True"
          SHOW_TIMEZONE: "True"
          SHOW_LOC_CHART: "True"